function buildNavigationUrl(query){
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}

window.buildNavigationUrl = buildNavigationUrl;

window.fallbackContacts = {
  tcdd_support: {
    id: 'tcdd_support',
    operator: 'TCDD',
    name: 'TCDD Destek Hizmetleri / Tesis İletişim',
    phone1: '0312 520 49 26',
    phone2: '0312 520 49 36',
    address: 'Hacı Bayram Mahallesi, Hipodrom Caddesi No: 3, Altındağ / Ankara',
    navigationQuery: 'Hacı Bayram Mahallesi Hipodrom Caddesi No 3 Altındağ Ankara',
    navigationUrl: buildNavigationUrl('Hacı Bayram Mahallesi Hipodrom Caddesi No 3 Altındağ Ankara'),
    sourceType: 'official'
  },
  demiryolis_genel_merkez: {
    id: 'demiryolis_genel_merkez',
    operator: 'DEMİRYOL-İŞ',
    name: 'DEMİRYOL-İŞ Sendikası Genel Merkez',
    phone1: '+90 312 231 80 30',
    phone2: '+90 312 231 80 32',
    address: 'Necatibey Caddesi, Sezenler Sokak No:5, Sıhhiye, Ankara',
    navigationQuery: 'Necatibey Caddesi Sezenler Sokak No 5 Sıhhiye Ankara',
    navigationUrl: buildNavigationUrl('Necatibey Caddesi Sezenler Sokak No 5 Sıhhiye Ankara'),
    sourceType: 'official'
  }
};

window.railwayFacilities = [
  {
    id: 'tcdd-akcay-1',
    operator: 'TCDD',
    category: 'egitim_ve_dinlenme_tesisi',
    name: 'Akçay 1 Normal Eğitim ve Dinlenme Tesisi',
    city: 'Balıkesir',
    district: 'Edremit',
    status: 'active',
    officialPublicContact: true,
    phone: '0 266 384 10 63',
    address: 'Akçay Mahallesi, Akçay Caddesi, 107. Sokak No: 1, Edremit / Balıkesir',
    navigationQuery: 'Akçay Mahallesi Akçay Caddesi 107. Sokak No 1 Edremit Balıkesir',
    navigationUrl: buildNavigationUrl('Akçay Mahallesi Akçay Caddesi 107. Sokak No 1 Edremit Balıkesir'),
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-akcay-2',
    operator: 'TCDD',
    category: 'egitim_ve_dinlenme_tesisi',
    name: 'Akçay 2 Ekonomik Eğitim ve Dinlenme Tesisi',
    city: 'Balıkesir',
    district: 'Edremit',
    status: 'active',
    officialPublicContact: true,
    phone: '0 266 384 10 63',
    address: 'Akçay Mahallesi, Akçay Caddesi, 107. Sokak No: 1, Edremit / Balıkesir',
    navigationQuery: 'Akçay Mahallesi Akçay Caddesi 107. Sokak No 1 Edremit Balıkesir',
    navigationUrl: buildNavigationUrl('Akçay Mahallesi Akçay Caddesi 107. Sokak No 1 Edremit Balıkesir'),
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-urla',
    operator: 'TCDD',
    category: 'egitim_ve_dinlenme_tesisi',
    name: 'Urla Eğitim ve Dinlenme Tesisi',
    city: 'İzmir',
    district: 'Urla / Çeşmealtı',
    status: 'active',
    officialPublicContact: true,
    phone: '0 232 752 10 67',
    address: 'Denizli Mahallesi, İskele Caddesi No: 1, Çeşmealtı, Urla / İzmir',
    navigationQuery: 'Denizli Mahallesi İskele Caddesi No 1 Çeşmealtı Urla İzmir',
    navigationUrl: buildNavigationUrl('Denizli Mahallesi İskele Caddesi No 1 Çeşmealtı Urla İzmir'),
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-arsuz',
    operator: 'TCDD',
    category: 'egitim_ve_dinlenme_tesisi',
    name: 'Arsuz Eğitim ve Dinlenme Tesisi',
    city: 'Hatay',
    district: 'Arsuz',
    status: 'active',
    officialPublicContact: true,
    phone: '0 326 643 20 09',
    address: 'Gözcüler Mahallesi, Cumhuriyet Caddesi No: 126, Arsuz / Hatay',
    navigationQuery: 'Gözcüler Mahallesi Cumhuriyet Caddesi No 126 Arsuz Hatay',
    navigationUrl: buildNavigationUrl('Gözcüler Mahallesi Cumhuriyet Caddesi No 126 Arsuz Hatay'),
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-fenerbahce',
    operator: 'TCDD',
    category: 'misafirhane_egitim_dinlenme',
    name: 'Fenerbahçe Eğitim ve Dinlenme Tesisi',
    city: null,
    district: null,
    status: 'active_listed_in_2026_tariff',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: '2026 ücret duyurusunda listeleniyor. Eğitim programları dışında müsaitlik durumuna göre konaklama veriliyor; ön rezervasyon yapılmıyor.',
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-afyon',
    operator: 'TCDD',
    category: 'misafirhane',
    name: 'Afyon Misafirhanesi',
    city: 'Afyonkarahisar',
    district: null,
    status: 'active_listed_in_2026_tariff',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-konya',
    operator: 'TCDD',
    category: 'misafirhane',
    name: 'Konya Misafirhanesi',
    city: 'Konya',
    district: null,
    status: 'active_listed_in_2026_tariff',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-sivas',
    operator: 'TCDD',
    category: 'misafirhane',
    name: 'Sivas Misafirhanesi',
    city: 'Sivas',
    district: null,
    status: 'active_listed_in_2026_tariff',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: '2026 ücret duyurusunda standart olmayan oda ücreti notu geçen tesislerden biri.',
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-izmir-basmane',
    operator: 'TCDD',
    category: 'misafirhane',
    name: 'İzmir / Basmane Misafirhanesi',
    city: 'İzmir',
    district: 'Basmane',
    status: 'active_listed_in_2026_tariff',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-adana',
    operator: 'TCDD',
    category: 'misafirhane',
    name: 'Adana Misafirhanesi',
    city: 'Adana',
    district: null,
    status: 'temporarily_closed',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: '2026 ücret duyurusuna göre tadilat/açılış işlemleri tamamlanıncaya kadar hizmet veremiyor.',
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-haydarpasa',
    operator: 'TCDD',
    category: 'misafirhane',
    name: 'Haydarpaşa Misafirhanesi',
    city: 'İstanbul',
    district: 'Haydarpaşa',
    status: 'closed_rebuild_pending',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: '2026 ücret duyurusuna göre yıkılmış durumda; yenisi yapılıp hizmete açılırsa ayrıca ücret belirlenecek.',
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'tcdd-malatya',
    operator: 'TCDD',
    category: 'misafirhane',
    name: 'Malatya Misafirhanesi',
    city: 'Malatya',
    district: null,
    status: 'closed_after_2023_earthquake',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: '2026 ücret duyurusuna göre 06.02.2023 depremlerinde hasar aldığı için hizmet veremiyor.',
    fallbackContactId: 'tcdd_support',
    sourceType: 'official'
  },
  {
    id: 'demiryolis-didim',
    operator: 'DEMİRYOL-İŞ',
    category: 'egitim_ve_dinlenme_tesisi',
    name: 'Didim Eğitim ve Dinlenme Tesisi',
    city: null,
    district: null,
    status: 'listed_on_official_site',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: 'Resmi sendika sitesinde tesis adı listeleniyor; kamuya açık telefon/adres bilgisi görünmedi.',
    fallbackContactId: 'demiryolis_genel_merkez',
    sourceType: 'official'
  },
  {
    id: 'demiryolis-sakran',
    operator: 'DEMİRYOL-İŞ',
    category: 'sosyal_tesis',
    name: 'Grand Demiryol-İş Şakran Tesisi',
    city: null,
    district: null,
    status: 'listed_on_official_site',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: 'Resmi sendika sitesinde tesis adı listeleniyor; kamuya açık telefon/adres bilgisi görünmedi.',
    fallbackContactId: 'demiryolis_genel_merkez',
    sourceType: 'official'
  },
  {
    id: 'demiryolis-ankara',
    operator: 'DEMİRYOL-İŞ',
    category: 'misafirhane',
    name: 'Ankara Misafirhanesi',
    city: 'Ankara',
    district: null,
    status: 'listed_on_official_site',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: 'Resmi sendika sitesinde tesis adı listeleniyor; kamuya açık telefon/adres bilgisi görünmedi.',
    fallbackContactId: 'demiryolis_genel_merkez',
    sourceType: 'official'
  },
  {
    id: 'demiryolis-haydarpasa',
    operator: 'DEMİRYOL-İŞ',
    category: 'misafirhane',
    name: 'Haydarpaşa Misafirhanesi',
    city: 'İstanbul',
    district: 'Haydarpaşa',
    status: 'listed_on_official_site',
    officialPublicContact: false,
    phone: null,
    address: null,
    navigationQuery: null,
    navigationUrl: null,
    note: 'Resmi sendika sitesinde tesis adı listeleniyor; kamuya açık telefon/adres bilgisi görünmedi.',
    fallbackContactId: 'demiryolis_genel_merkez',
    sourceType: 'official'
  }
];
